### ISSUE TITLE
Move libnixstore to independent repo

### ISSUE THREAD

**Issue by kip93** [nix-community/harmonia#377]
This seems like something that could benefit from being moved since it seems to be forgotten about currently. Current published version still points to the old repo even though many changes have been done since. Having it in its own repo would mean more frequent publishing would be done because otherwise you'd not be able to use those chages here.

Willing to put in the work to move this, but I of course don't have the required permissions to do the updated publishing on crates.io. And it probably requires moving ownership of the cargo project itself in crates.io (is there a nix-community group in crates.io?)

**Comment by Mic92** [comment]
I am fine with that but i don't have access to crates.io either. Maybe @Conni2461 or @dasj have access as this crate was published in the helsinki systems fork rather than here.
These day one probably would use the more stable c interface rather than the c++ version, also those bindings are probably not feature comparable.
